### ISSUE TITLE
Error on .hdf file content

### ISSUE THREAD

**Issue by jerome-colin** [jerome-colin/mtools#17]
ERROR No subdataset found for band name band03 in /work/CESBIO/projects/Maja/ACIX/References/S2/Ouarzazate/refsrs2-L1C_T29RPQ_A003695_20171120T110332-Ouarzazate.hdf

```
Traceback (most recent call last):
  File "acix_validate.py", line 169, in <module>
    main()
  File "acix_validate.py", line 78, in main
    b_ref = p_ref.get_band(p_ref.find_band(bdef_acix[band_id][0]), scalef=p_ref.sre_sc
alef)
  File "/work/CESBIO/projects/Maja/ACIX/mtools/common/Product.py", line 260, in get_ba
nd
    return gdal.Open(self.content_list[fband][0], gdal.GA_ReadOnly).ReadAsArray() / sc
alef
TypeError: list indices must be integers or slices, not NoneType
```

**Comment by jerome-colin** [comment]
Ouarzazate/refsrs2-L1C_T29RPQ_A003695_20171120T110332-Ouarzazate.hdf is corrupted (checked with hdfview). A better behavior than exit(1) could be to just skip it.

**Comment by jerome-colin** [comment]
Solved. Check logs for msg like: 
`2020-05-28 11:51:25,660 WARNING Got an error with product for 20180620 between /home/colinj/code/mtools/test_data/Reference/Brussels/refsrs2-L1C_T31UES_A015635_20180620T105211-Brussels.hdf and /home/colinj/code/mtools/test_data/Maja/Brussels/SENTINEL2A_20180620-105211-086_L2A_T31UES_C_V1-0
`
